src/modules/settingsPage.js
Relevant-to: https://github.com/hohMiyazawa/Automail/issues/26#issuecomment-623677462
Signed-off-by: Jacob Hrbek <kreyren@member.fsf.org>
=> settingsPage: Inform about the requirement for persistent cookies

src/css/global.css
I happened to notice the errors in devtools.
=> Minor fixes to global css

src/modules/meanScoreBack.js
=> Fix regex for milestones

src/modules/likesAndTwitter.js
Fixes an issue I found where some of the users were getting duplicated after liking the thread (I forgot to test this before.)
Also fixed a minor issue where unliking a thread wouldn't remove yourself from the list.
=> Forum like fixes

src/css/global.css, src/modules/anisongs.js
- Fixed stripping of numbers from song titles due to MAL update
- Adjusted the formatting of the song divs to have similar spacing as tags on the page
- Reworked the api calls
- Replaced the anilist call with `generalAPIcall`
- Replaced the `GM_xmlhttpRequest` wrapper with `fetch`
- *Note: `GM_xmlhttpRequest` is userscript specific so I imagine this module hasn't worked for addon users*
=> More anisongs improvements

src/modules/replaceStaffRoles.js
- adds native routing to custom staff pages
=> Even more native routing

src/css/global.css, src/modules/moreImports.js, src/utilities/levDist.js
This looks promising. What's the status of it, @nzoba?
=> Improvements of Anime-Planet lists import

src/modules/anisongs.js
fixes a couple issues introduced with https://github.com/hohMiyazawa/Automail/commit/156fd18f0557a7d6776a8188e92c1cf8971cf837
=> Fix anisongs visual bugs

src/css/global.css
fixes some slight styling differences with the enhanced feeds
=> enhanceSocialFeedTab: adjust action styling

src/modules/addActivityTimeline.js, src/modules/addComparisionPage.js, src/modules/addFollowCount.js, src/modules/addForumMedia.js, src/modules/addForumMediaNowAWC.js, src/modules/addForumMediaTitle.js, src/modules/addMALscore.js
migrates the following to `anilistAPI`:
- addActivityTimeline
- addComparisionPage
- addFollowCount
- addForumMedia
- also added native routing
- addForumMediaNowAWC
- addForumMediaTitle
- addMALscore
- also added native routing
(i tested these yesterday before the api shutdown)
=> api v2 migration - part 1

src/graphql.js
catch errors if fetch itself fails
=> anilistAPI: handle error if request fails

src/modules/addActivityLinks.js
I forgot to change this back to ms when I was writing the api.
=> addActivityLinks: fix cache duration

src/modules/anisongs.js
- fix issue introduced with https://github.com/hohMiyazawa/Automail/commit/c0ef7cfdd8346582ddc21586caa54b4c5fa995c2
- fix `no-use-before-define` lint issues
=> anisongs: minor fixes

src/css/global.css, src/modules/addActivityTimeline.js
- used grid instead of absolute positioning for activities
- adjustments to margins/padding to better match the site style
- timeline gap separators now use the horizontal bar character instead of a triple dash
- switch to `pageInfo.hasNextPage` to avoid potential issues with `pageInfo.lastPage`
- small change to the trimmed input in case it would affect the `cacheKey`
Preview:
=> addActivityTimeline: visual adjustments

src/css/global.css
it currently made the button float too far to the right, so I removed the classes affecting it.
=> fix studio fav button position

src/css/global.css, src/modules/addEntryScore.js
Added progress totals
- For clarity and to match home page behaviour/display
Update hohMediaScore css
- Text looked too close to edit button
- Font size now matches rest of the top text block (Potentially personal pref)
Preview:
=> Media progress totals

src/modules/altBanner.js
Updated CSS due to .banner appearing on submission pages
Also small refactor
=> altBanner fixed bug - Updated css for submission page clash

src/modules/mangaGuess.js
Forgot to remove debugging line
=> mangaGuess Cleanup

src/data/languages/English.json, src/modules/altBanner.js
Reworked the module to ignore media that don't have banners and to reduce the observer scope.
Also added the translation keys
=> altBanner Rework + keys

src/data/languages/French.json
Hi,
I synced the French keys with the recent Italian ones
=> Added new keys to the French localization

src/css/verticalNav.css
Reverts hohMiyazawa/Automail#226
=> Revert "Fixed title/status overflow in verticalNav"

src/modules/noSequel.js
=> noSequel: fix id

src/css/verticalNav.css
Narrow scope for previous fix, no longer impacts list editor
https://github.com/hohMiyazawa/Automail/pull/226
=> Fix status overflow v2

src/data/languages/English.json, src/modules/hideScores.js
Optimised a few things
- Reduced mutation scope
- Ignore Not Yet Released media
- Ignore already processed embed cards
- Added translation keys
=> hideScores optimisation & translation keys

src/queries/BroomCat.js
- switched to apiv2 and added additional rate limit handling
- it will now retry after the wait period is over
- added the ability to sort by "date added" instead of by popularity
=> BroomCat: upgrade to apiv2

src/queries/BroomCat.js
Missed an extra one when the throttle was added
=> BroomCat: setTimeout id

package.json
I ended up encountering [a bug](https://github.com/vercel/serve/issues/575) while using serve that kept crashing the server after a period of time (~30m), so I switched back to [http-server](https://github.com/http-party/http-server) which was originally used in the guide I was following in #248 (my bad)
=> Switch dev server to http-server

src/queries/relatedManga.js
=> relatedManga: add option to filter light novels

src/modules/addRelationStatusDot.js
There is currently a small bug where only the 1st page of recommendations (up to 25 cards) gets a status dot, everything else afterwards does not.
In the above screenshot the 3rd last and last cards are supposed to have a dot (number 26 and 28).
Code is now updated to work for any number of recommendation pages, it has also been switched over to using a mutation observer for a more elegant/performant solution.
=> Fix recommendations status dot bug > 25 cards

src/queries/popularFavourites.js
=> popularFavourites: Fix undefined key

src/data/languages/English.json, src/modules/recommendationsFade.js
Update to previous PR https://github.com/hohMiyazawa/Automail/pull/294
- Converted into an optional module
- Small update to not fade the title
- Added English key
**Preview:**
=> Add recommendations fade for media already in list (Module)
