hohMiyazawa/Automail

README.md
src/automail.m4

Also add a copyright notice in both the README and final build.
The main benefit of using SPDX IDs is that `GPL-3.0-or-later` is much more clear than "GPLv3" and is also standardized.

Use SPDX IDs for communicating license info

---

src/css/global.css
src/css/notifications.css
src/modules/enhanceNotifications.js

Puts the image source link into the img element's src field and gave it the object-fit styling property to behave the same as background-size. This removes the border that appears when the browser thinks it isn't displaying an image in the img element. This is also better symantic html than just changing the element from img to div which would have the same effect.

Remove borders around images in notifications

---

src/cache.js

I think this fully fixes #49 as this has not been working for me for a while, even with persistent storage enabled.
Since the list cache is stored separately for each media type and from what I understand the lock is there to prevent other functions from trying to interact when it's in use, the extra lock comparison is not needed.
`addMoreStats` basically asks for both lists the moment the stats subpage is loaded so both cache locks will be set to true around the same time and the `forceUpdate` never happens.

Fix additional stats not working as own user

---

src/modules/profileBackground.js

When I reset my script settings I noticed a few invalid network requests were being sent from this module so I changed the regex to be strictly alphanumeric.
e.g. stuff like `hohProfileBackgroundhoh/stats/anime/overview` was being set in session storage

Fix user regex for profile backgrounds

---

src/css/global.css
src/modules/replaceStaffRoles.js

First change fixes the margins on replies when using the social feed filters.
Before|After
--|--
Second change reduces the spacing slightly between sections on staff pages.

Styling fixes

---

src/css/global.css
src/modules/forumLikes.js
src/modules/likesAndTwitter.js

Copied the code for displaying more likes on thread comments to make it work for the main thread post.
Main difference is I changed the API call to only get the first 20 users, so it doesn't try adding hundreds of more users to the `.users` list that won't be displayed anyways.
The other change prevents the list of users from appearing when hovering over the user avatars.

Forum thread likes

---

src/css/global.css
src/modules/anisongs.js

- Changed getting video links to the api provided by [Animethemes.moe](https://staging.animethemes.moe/api/docs/) instead of html parsing of reddit
- This directly gets OP/ED links for the anime (using anilist id) instead of every anime in its release year
- Fixed parsing of song title data from jikan (e.g. [Evangelion EDs](https://anilist.co/anime/30/Shin-Seiki-Evangelion/))
- Limited the width of videos to fit within the column (allows an OP and ED to be open side-by-side)
Somewhat related, there's a bug introduced with dce1d2e37381e4db6fc9c6f16a1d8af69fbd8b2e where anisongs data can be written to the `automail` indexeddb instead of `Anisongs` and vice-versa depending on how the site is navigated. I didn't fix it for this PR as I'm unsure if it's intended to have separate databases …

Anisongs improvements

---

src/modules/anisongs.js

Continued from #100
>As the API usage is now different, I think it makes sense to use the automail storage instead of the anisongs one.
The script should now use the config that runs from https://github.com/hohMiyazawa/Automail/blob/master/src/cache.js before the modules.

Fix indexeddb conflict

---

src/modules/addMALscore.js

Fixes two small issues:
- User recs that were too long on MAL were hidden with html that wasn't cleaned properly when displayed
- e.g. https://anilist.co/manga/64793/Joshi-Kouhei/
- User recs containing newlines were omitted entirely

Fix mal recs description parsing

---

src/controller.js
src/data/legacyModuleDescriptions.json
src/modules/enhanceTags.js
src/settings.js

- migrated to module format
- fixed a bug where custom tags (i.e. nsfw tags) would eventually fail to show its description
- what would happen is the description would fill normally until the tag input box was cleared, then the site would delete the blank node. so when input was entered again a new node was created without the `onmouseover` and `onmouseout` handlers.
- changed the main script to only run once the "add tag" icon has been clicked
- removed message about adding missing tag descriptions

Migrate tag descriptions to module

---

src/modules/extraFavs.js

- changed the fav container to set `max-height` instead of `height`
- fixes an issue where the container would remain the same height when navigating from a profile with extra favs to one without
- ~copied the vue ids from the first fav found to extra favs so the native styling is used~
- added `onmouseout` event to extra favs so the tooltip disappears properly
- added native routing to extra favs
Sidenote: I noticed https://github.com/hohMiyazawa/Automail/commit/b4ba4884553aa3635b97cdce8571a5173ebf458e was applied for anime favs but not for manga. I don't have a profile to test for (extra) manga favs so I don't know if the same fix is needed or not.

Extra favs enhancements

---

src/modules/feedListLikes.js

In certain cases where an activity's like count is 0, the count element is empty and gets parsed improperly. This would lead to the script continuing to run every time the like area was hovered over and consequently several duplicate requests spammed the api.

feedListLikes: fix type issue

---

src/cache.js
src/graphql.js

This creates a new Anilist api wrapper that could replace the existing `generalAPIcall` and `authAPIcall` functions. The existing wrapper requires the use of many nested callbacks when creating multiple requests leading to code that becomes difficult to read/understand (imo).
I figured it wouldn't be worthwhile to change the existing wrapper and instead wrote a new one in parallel, that does not depend on the existing implementation. It's not a drop-in replacement, so module code would have to be reworked to use it (somewhat similar to the `exportModule` migration.)
A few differences introduced with `anilistAPI`:
- Asynchronous
- Request options are sent in a single argument
- Added authentication as an option
- Added internal api as an option
- Cache backed by localforage
- Rate limiting …

Api rewrite

---

src/modules/anisongs.js

- use new api
- use a separate named store for the cache (same as what `anilistAPI` does now)
- upgrade to [Jikan v4](https://docs.api.jikan.moe/)
- using the new [`/themes` endpoint](https://docs.api.jikan.moe/#operation/getAnimeThemes) will return a smaller data response
- also removed obsolete patch for the themes placeholder issue

anisongs: upgrade to api v2

---

.eslintignore
.eslintrc.json
.gitignore
package.json

Fixes #137 
- initialized a Node.js project
- added [eslint](https://github.com/eslint/eslint) and [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) for linting
How to use:
1. Install [Node.js](https://nodejs.org/en/) LTS for your platform
2. Open terminal and enter the Automail directory
3. Run `npm install`
4. Run `npm run lint` to lint all JS project files
- Or `npm run lint-build` to lint just the compiled userscript
Installing globally (alternative):
Follow the same steps as above, except replace step 3 with:
- Run `npm install -g eslint@8 eslint-plugin-compat@4`
Optional:
- Install an [integration](https://eslint.org/docs/user-guide/integrations#editors) for your code editor
- will apply linting as you edit open files instead of needing to run the terminal …

Add eslint

---

src/modules/enhanceNotifications.js

related to #110 
it was breaking on a notification about a deleted media (which has no link element so therefore no `href`)
so it's kinda working now...
idk what to do about the essays though

Fix enhanced notifications for deleted media

---

src/cache.js
src/modules/addMoreStats.js
src/modules/drawListStuff.js

migrates both `addMoreStats` and `cache.js` to anilistAPI
(since cache.js is primarily used by addMoreStats, I did both at once)
also includes a change that splits up the list calls sent by cache.js
- Before: 2 combined anime + manga calls are made when force updating
- After: 1 anime call and 1 manga call are made when force updating
sidenote: this kind of helps performance when viewing my own stats page, but there still seems to be something hampering performance overall

addMoreStats: upgrade to api v2

---

src/modules/addMediaReviewConfidence.js

Adapted from https://github.com/hohMiyazawa/Automail/blob/4c1ad3e78ebd64286b4c3e96a072c96dcabe4efa/src/modules/addReviewConfidence.js, this applies the review confidence score to the media review subpages. Since it's a different url scheme and page structure, I made a new module instead of modifying the original.
Also added the ability to load more scores if the "load more" button is clicked (only shows up on pages if there are enough reviews for it.) I might copy this change back to the original at some point.
e.g. https://anilist.co/anime/101922/Kimetsu-no-Yaiba/reviews

add review confidence for media pages

---

src/controller.js
src/css/global.css
src/modules/addReviewConfidence.js
src/modules/character.js
src/modules/characterBrowse.js
src/utilities.js

character:
- migrated to module
- removed old references (likely used before the page redesign)
- reworked to run only when the count exceeds 1000 favs
- prevents extra requests from being sent
characterBrowse:
- reworked to use a MutationObserver to watch for more results loading instead of setTimeout
- fixed an issue where the main browse page didn't load all fav counts
- main browse loads a single batch of 30, `/favorites` loads batches of 20
utilities:
- moved watchElem here so it can be more widely used

character/characterBrowse: upgrade to api v2

---

src/modules/replaceStaffRoles.js

Fixes an issue where an inaccurate `pageInfo.lastPage` will cause the request loop to send many unnecessary requests to the server.

replaceStaffRoles: fix api request loop

---

src/css/global.css
src/modules/filterStaffTabs.js

Changed the design to better match the search bar used on staff pages as well as to fit better on the media page itself.
- made use of grid for better positioning on the page
- used `watchElem` to replace the use of the waiter function
- changed the placeholder text to more explicitly describe what can be filtered
- I didn't change the translation key since it is also being used by the media list filter box (might need to make a new key for that)
Preview:

filterStaffTabs: visual upgrade

---

src/modules/anisongs.js

The animethemes api is now stable.
(new docs link for reference: https://api-docs.animethemes.moe )

anisongs: update animethemes url

---

src/queries/BroomCat.js

- fixed configs that deal with media descriptions to handle null values
- switch to `hasNextPage` to avoid extra requests

BroomCat fixes

---

src/css/global.css
src/modules/viewAdvancedScores.js

Updated the Advanced Scores tooltip style
- Matches other Anilist tooltip styles (notes etc.)
- Tooltip now appears instantly on hover rather than default delayed behaviour
- Added Justify for nicer scoring alignment
Preview:

Update Advanced Scores tooltip style

---

.eslintignore
package.json

Ignores other build variants (can be overriden with `--no-ignore` if needed)

eslint: ignore build directory

---

src/graphql.js

- Changed to a normal console output as throwing was unnecessary
- (I was not aware of the burst limit previously and assumed only faulty modules could reach this point)
- Add a reset limit manually if a certain `NetworkError` is received
- Most likely due to the current state of the server, when the burst limit is reached the api stops sending the right CORS header and ends up creating network errors instead of HTTP errors which contain no useful responses. So until that's resolved I think it's safe to reset the limit whenever this error is caught.

anilistAPI: adjust rate limit handling

---

src/modules/directEditorAccess.js

Fixed a visual bug where after the click event, the dropdown box shows up on top of the editor window
Screenshot of bug

Fix dropdown bug for directEditorAccess

---

src/modules/hideScores.js

Added ability to click Avg/Mean scores on media pages to get them to stay displayed. 
Added/updated additional css for other browse views. Now applies to all 3 views - Compact cards (Hidden), expanded cards (spoiler), list rows (spoiler).
Cleaned up/simplified code.
There is a small bug on some media (eg. CSM for me) where the `.overview .follow .score` style color is being overridden by another module so text always shows. Not sure what to do about it so for now left it at opacity: 0 on no hover.

Update hideScores - Add onclick scores, add missing browse, cleanup

---

src/modules/altBanner.js

New module to change the banner style. 
- Currently banners look bad on window/screen resolutions wider than 1920 pixels with extreme stretching and cropping.
- Only made it for media pages since it won't work as well on user profiles due to banner resolution/ratio not being enforced in uploads. (And most people not following the guideline). Though let me know if you think it should still be adapted for profiles.
- Made sure it is still compatible with banner downloads and banner shadows/no shadows.
- Discovered that AL also hard crops the banner & header height by 58 pixels (`.banner{margin-top: -58px;}`) for resolutions wider than 760px. I made this 0 too, though I'm not sure if it breaks anything (so far it doesn't seem like it).
Screenshots:
Option off
Option on
Option off
Option on …

Add module altBanner

---

src/modules/hideScores.js

Forgot to add `observer.disconnect()` back in. No longer need to observe if we have found and updated both Average and Mean scores.
**Side note:** Reason we need the observer is that sometimes the Mean score loads after the Average score, plus they don't have unique class names. However, some media may have a mean score but not an average score, so observers will never be disconnected for these (Potentially bad but at least there aren't many of them).
I'm also trying to avoid setTimeout/setInterval

hideScores - add back observer.disconnect

---

src/modules/hideScores.js

Fixed bug similar to that found in https://github.com/hohMiyazawa/Automail/pull/200 and https://github.com/hohMiyazawa/Automail/commit/6b7efec7b3590d9e0fd3926424eab10fccd4017d
Some updated page elements (sidebar) retain their attributes between page loads, so need to add a cleanup check (cannot reuse).
For example, on [this page](https://anilist.co/anime/127230/Chainsaw-Man/), clicking on the Source relation shows this on the next page
Also refactored/simplified code again with new class/css

hideScores - Fix persistent element page transition bug

---

src/css/global.css

For https://github.com/hohMiyazawa/Automail/issues/213
Tested as working on Android (Firefox Nightly)
iOS pending/unknown
No effect on desktop browsers
Future title tooltips or touchscreen/stylus specific CSS can be whitelisted in this block

Add timestamp display on touch for touchscreens

---

src/css/displayBox.css
src/css/global.css
src/css/smallScreens.css

Some more mobile fixes
hohDisplayBox gets cut off at the side on small screens due to fixed positioning, 
Updated to center the box for both small widths and heights. Also fixed the box getting covered by pop up cover images.
Side note: Dragging/re-sizing the box does not currently work on touchscreens. Super long notes are still sometimes cut off at bottom on normal resolutions.
Fixed tooltips not working in user lists (`.repeat` and `hohAdvancedDollar`). Notes can use the display box.
Fix needs to be applied to both touchscreens and small screens as both can occur separately.
Note: Only works in Semi-compact list view. Compact view is just natively broken with the edit button in the way, not sure how to fix that

Touchscreen/Small screen fixes - hohDisplayBox + tooltips

---

src/css/verticalNav.css

Fixed verticalNav titles/status at certain lengths overflowing into the time on feeds (both single column and double column)
Also I think it would be a good idea to have another verticalNav option without all the extra styling to the body (but maybe it's just me)

Fixed title/status overflow in verticalNav

---

src/makefile

I had noticed whenever running the build script the addon zip was always missing the manifest file. I don't know if it's an issue with the zip utility or a platform issue, so I fixed it by explicitly copying the manifest into the directory before creating the archive.

Copy manifest to addon build

---

src/modules/noSequel.js

- Fixed a translation key (it looked fixed in the commit history oddly enough)
- Fixed sequel hiding on the browse page when using "chart" mode (the middle display option)
- Unlike the other two display options, the link is attached under a different child element

noSequel: bugfixes

---

src/modules/imageFreeEditor.js

Also touched up the styling to look more even with the rest of the modal.
Example: https://anilist.co/manga/110801/Honzuki-no-Gekokujou-Shisho-ni-Naru-Tame-ni-wa-Shudan-wo-Erandeiraremasen-Dai-3bu--Ryoushu-no-Youjo/
Before|After
--|--
Mobile (pseudo)
Before|After
--|--

imageFreeEditor: fix styling for long titles

---

src/modules/tweets.js

Fixes #250 
After testing with FireMonkey, I found the check for `window.GM_xmlhttpRequest` was failing leaving the loading placeholder as described in the above issue. Since the check isn't that reliable for detecting if the script is running as an addon, I changed it to check for `browser`/`chrome` instead, which are extension-only globals.
That aside, iirc the restriction was a FF AMO thing, and since the addon is no longer updated there the check is probably not needed.

Fix Twitter embed check

---

src/modules/addMALscore.js
src/modules/addMoreStats.js
src/utilities.js

Fixes #251
- used [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) to resolve Xray error
- a shallow clone like ```const entry = {..._entry}``` didn't work because it would still error on the `entry.media` object
- todo: look for a polyfill since it's a newer feature
- no longer depend on cache.js in stats module (mostly)
- apiv2 can handle caching lists in a similar way
- (this didn't have any effect on the main issue, though i changed it to rule it out anyways)
- fixed another GM xhr check for mal recs
- removed the xhr backup as that will fail anyways because of cors
- (might look into using jikan for this instead)

Fix FireMonkey compatibility

---

src/modules/addMediaReviewConfidence.js

Small change to the regex for matching reviews since it looks like confidence scores aren't showing up on pages whenever an English character isn't present in the media title.

Fix for confidence scores with Japanese titles

---

src/controller.js
src/data/legacyModuleDescriptions.json
src/modules/addBrowseFilters.js
src/settings.js

What started as a fix for the custom filters disappearing ended up being a rework of the whole thing.
- converted to module
- apply custom sort filters using builtin vue object
- I found that modifying the `sortOptions` object will immediately update the sort dropdown with any changes
- (any valid `MediaSort` enum can be added to it, though not all of them work well)
- added a few new sorts that allow reverse sorting of some of the default options
Anime Browse
Manga Browse

Rework browseFilters

---

src/data/languages/English.json
src/data/languages/Norwegian.json

There were 2 instances of `hollowHearts_description` in the English section, and the second one (in Norwegian) was overwriting it.
Likewise, this description was missing from the Norwegian section.

Correct English description for Hollow Hearts setting
